export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const CONTEXT_MENU_OPEN = 'CONTEXT_MENU_OPEN';
export const CONTEXT_MENU_CLOSE = 'CONTEXT_MENU_CLOSE';
export const CONTEXT_MENU_REOPEN = 'CONTEXT_MENU_REOPEN';

export const NOTIFICATION_OPEN = 'NOTIFICATION_OPEN';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

export const GET_POSTS = 'GET_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_NEWS = 'GET_NEWS';
